services:
    # run frontend-prod build on Port 5000
    app:
        image: nish1896/nishant-profile
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:80'
        # env_file: .env

    # run frontend in dev mode on Port 3000, with hot reloading
    dev:
        image: nish1896/nishant-profile-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - '/app/node_modules'
            - './:/app/'